---
name: Naveen
surname: Kannan
position: "Research Associate"
address: "Cleveland, Ohio"
www: naveenkannan.netlify.app
phone: +1 973 519 5397
email: "naveen.kannan12@gmail.com"
github: naveenk2022
linkedin: naveen-kannan-177120118
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Data Scientist experienced with data analysis, visualization, building pipelines, automation and Data Engineering. I have a strong passion for coding, visualization and automation, and I compiled this CV with code. United States Permanent Resident."
headcolor: 990000
output: vitae::awesomecv
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(tinytex.verbose = TRUE)
library(vitae)
library(kableExtra)
library(here)
library(tibble)
library(readr)
library(glue)
source(file = here("data","data.r"))
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where, ~ Detail,
  "MS in Biomedical and Health Informatics", "JANUARY 2022 – AUGUST 2023", "Case Western Reserve University", "Cleveland, Ohio","GPA-3.9" ,
  "Bachelor of Medicine and Bachelor of Surgery", "SEPTEMBER 2016 - MARCH 2020", "Madras Medical College", "Chennai, India","GPA-4.0" 
) %>% 
  detailed_entries(Institution, Year, Degree, Where,Detail)
```

# Experience

```{r Research, results = "asis"}

experience %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = ""),
    where = where, .protect = F
  )

```

# Technical Skills 

```{r SKILLS}

skills %>%
  detailed_entries(
    with = area,
    what = skills
  )

```




